# Generated by Django 6.0.3 on 2026-04-07 15:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='archivo'),
        ),
    ]
